#!/bin/bash

basedir="$HOME/.gammagames"
linkdir="$basedir/links"
datadir="$basedir/data"

VERSION="0.1.1"

#creating directories
mkdir -p "$basedir"
mkdir -p "$linkdir"
mkdir -p "$datadir"

show_help() {
    cat <<EOF
    this is help
EOF
}

show_version() {
    echo -e "Gamma - CLI game manager\nversion $VERSION"
}

get_title_from_index() {
    local titles=("$linkdir"/*)
    echo "${titles[$(($1-1))]}"
}


case "$1" in
    start)
        if [[ "$2" == "index" ]]; then
            if [[ ! "$3" =~ ^[0-9]+$ ]]; then
                echo "Invalid index"
                exit 1
            fi
            #runs at index
            "$linkdir/$(get_title_from_index $3)"
        elif [ ! -f "$linkdir/$2" ]; then
            echo "File doesn't exist"
        fi
        #runs normally
        "$linkdir/'$3'"
        ;;
    list)
        titles=("$linkdir"/*)
        index=0
        for title in "${titles[@]}"; do
            echo "$((++index)) ${title##*/}"
        done
        #TODO
        #playtime
        #tags
        #size
        ;;
    rename)
        if [ ! -f "$linkdir/$2" ]; then
            echo "File not found"
        fi
        mv "$linkdir/$2" "$linkdir/$3"
        ;;
    path)
        case "$2" in
            add)
                echo "export PATH=\"\$PATH:$linkdir\"" >> ~/.bashrc
                source ~/.bashrc
                echo Added games to PATH
                ;;
            remove)
                grep -v "export PATH=\"\$PATH:$linkdir\"" ~/.bashrc > \
                    ~/.bashrc.gammatmp && mv ~/.bashrc.gammatmp ~/.bashrc
                source ~/.bashrc
                echo Removed games from PATH
                ;;
            *)
                if grep -q "export PATH=\"\$PATH:$linkdir\"" ~/.bashrc ; then
                    echo Games are in PATH. Use "gamma path remove" to remove them
                else

                    echo Games are not in PATH. Use "gamma path add" to remove them
                fi
                ;;
        esac
        ;;
    tag)
        if [ -z "$4" ]; then
            if [ -z "$2" || ! -f "$linkdir/$2" ]; then
                echo No title given or title does not exist
                exit 1
            elif [ ! -z "$3" ]; then
                echo "Not enough arguments given"
                exit 1
            fi
            "$linkdir/$2 tag"
        fi

        case "$3" in
            add)
                "$linkdir/$2 tag a $4"
                ;;
            remove)
                "$linkdir/$2 tag rm $4"
                ;;
            *)
                echo Invalid argument
                exit 1
                ;;
        esac
        ;;
    edit)
        if [ ! -f "$linkdir/$2" ]; then
            echo "File not found"
        fi
        vim "$linkdir/$2"
        ;;
    delete | del)
        if [[ "$2" == "index" ]]; then
            if [[ ! "$3" =~ ^[0-9]+$ ]]; then
                echo "Invalid index"
                exit 1
            fi
            #runs at index
            "$linkdir/$(get_title_from_index $3) del"
        elif [ ! -f "$linkdir/$2" ]; then
            echo "File not found"
        fi
        #runs normally
        "$linkdir/$3 del"
        ;;
    install)
        #TODO
        ;;
    help)
        show_help
        ;;
    version)
        show_version
        ;;
    *)
        show_help
        show_version
        ;;
esac
